actions:
  - name: Add Organization Name to tokens
    code: ./actions/Add Organization Name to tokens/code.js
    dependencies: []
    deployed: true
    runtime: node22
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
  - name: Trigger Progressive Profiling
    code: ./actions/Trigger Progressive Profiling/code.js
    dependencies: []
    deployed: true
    runtime: node18
    secrets: []
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: Add Organization Name to tokens
      display_name: Add Organization Name to tokens